package net.perfectdreams.butterscotch.android

import android.annotation.SuppressLint
import android.content.res.Configuration
import android.graphics.Color as AndroidColor
import android.os.Bundle
import android.view.View
import android.view.WindowManager
import android.webkit.WebChromeClient
import android.webkit.WebResourceRequest
import android.webkit.WebSettings
import android.webkit.WebView
import android.webkit.WebViewClient
import androidx.activity.ComponentActivity
import androidx.activity.compose.setContent
import androidx.activity.compose.BackHandler
import androidx.compose.foundation.background
import androidx.compose.foundation.gestures.awaitEachGesture
import androidx.compose.foundation.gestures.awaitFirstDown
import androidx.compose.foundation.gestures.waitForUpOrCancellation
import androidx.compose.foundation.layout.Box
import androidx.compose.foundation.layout.BoxWithConstraints
import androidx.compose.foundation.layout.BoxWithConstraintsScope
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.offset
import androidx.compose.foundation.layout.size
import androidx.compose.foundation.shape.CircleShape
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.runtime.DisposableEffect
import androidx.compose.runtime.LaunchedEffect
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.setValue
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.alpha
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.input.pointer.pointerInput
import androidx.compose.ui.platform.LocalConfiguration
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import androidx.compose.ui.viewinterop.AndroidView
import net.perfectdreams.butterscotch.android.layouts.GamepadElement
import net.perfectdreams.butterscotch.android.layouts.GamepadLayout
import net.perfectdreams.butterscotch.android.layouts.InputBinding
import net.perfectdreams.butterscotch.android.layouts.LayoutLibrary
import net.perfectdreams.butterscotch.android.library.GameEntry
import net.perfectdreams.butterscotch.android.library.GameLibrary
import net.perfectdreams.butterscotch.android.theme.ButterscotchAndroidTheme
import org.json.JSONObject
import java.io.File
import java.util.UUID

/**
 * Activity responsible for running imported HTML games.
 *
 * HTML games are stored in the same GameLibrary used by GameMaker games.
 * The importer records a relative entry point such as "index.html", and
 * this activity loads that file directly from the game's private bundle.
 *
 * The WebView is intentionally kept independent from the native GameMaker
 * runner. HTML games communicate with the Android host only through:
 *
 *  - the WebView itself;
 *  - the shared virtual gamepad layout system;
 *  - synthetic DOM keyboard events generated by HtmlKeyState.
 *
 * This keeps the HTML runtime completely separate from ButterscotchNative,
 * while still using the same launcher/library/layout infrastructure.
 */
class HtmlGameActivity : ComponentActivity() {

    companion object {
        const val EXTRA_GAME_ID = "game_id"

        private const val TAG = "HtmlGameActivity"
    }

    private var webView: WebView? = null

    private val pressedKeys = HtmlKeyState()

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)

        window.addFlags(WindowManager.LayoutParams.FLAG_KEEP_SCREEN_ON)

        hideSystemBars()

        val gameLibrary = Libraries.loadGameLibrary(applicationContext)
        val layoutLibrary = Libraries.loadLayoutLibrary(applicationContext)

        val gameId = intent
            .getStringExtra(EXTRA_GAME_ID)
            ?.let { value ->
                runCatching {
                    UUID.fromString(value)
                }.getOrNull()
            }

        if (gameId == null) {
            finish()
            return
        }

        val entry = gameLibrary.findById(gameId)

        if (entry == null || entry.gameType !is GameEntry.GameType.Html) {
            finish()
            return
        }

        setContent {
            ButterscotchAndroidTheme {
                HtmlGameContent(
                    entry = entry,
                    library = gameLibrary,
                    layoutLibrary = layoutLibrary,
                    onWebViewCreated = { view ->
                        webView = view
                    },
                    onKeyDown = { vk ->
                        webView?.let { view ->
                            pressedKeys.press(view, vk)
                        }
                    },
                    onKeyUp = { vk ->
                        webView?.let { view ->
                            pressedKeys.release(view, vk)
                        }
                    },
                    onReleaseAllKeys = {
                        webView?.let { view ->
                            pressedKeys.releaseAll(view)
                        } ?: pressedKeys.clear()
                    },
                    onExit = {
                        finish()
                    }
                )
            }
        }
    }

    override fun onPause() {
        pressedKeys.releaseAll(webView)
        super.onPause()
    }

    override fun onDestroy() {
        pressedKeys.releaseAll(webView)

        webView?.apply {
            stopLoading()
            loadUrl("about:blank")
            clearHistory()
            removeAllViews()
            destroy()
        }

        webView = null

        super.onDestroy()
    }

    override fun onWindowFocusChanged(hasFocus: Boolean) {
        super.onWindowFocusChanged(hasFocus)

        if (hasFocus) {
            hideSystemBars()
        }
    }

    private fun hideSystemBars() {
        window.decorView.systemUiVisibility =
            View.SYSTEM_UI_FLAG_FULLSCREEN or
                View.SYSTEM_UI_FLAG_HIDE_NAVIGATION or
                View.SYSTEM_UI_FLAG_IMMERSIVE_STICKY or
                View.SYSTEM_UI_FLAG_LAYOUT_FULLSCREEN or
                View.SYSTEM_UI_FLAG_LAYOUT_HIDE_NAVIGATION or
                View.SYSTEM_UI_FLAG_LAYOUT_STABLE
    }
}

@SuppressLint("SetJavaScriptEnabled")
@Composable
private fun HtmlGameContent(
    entry: GameEntry,
    library: GameLibrary,
    layoutLibrary: LayoutLibrary,
    onWebViewCreated: (WebView) -> Unit,
    onKeyDown: (Int) -> Unit,
    onKeyUp: (Int) -> Unit,
    onReleaseAllKeys: () -> Unit,
    onExit: () -> Unit
) {
    val gameType = entry.gameType as? GameEntry.GameType.Html
        ?: return

    val rootDirectory = library.bundleDir(entry)
    val entryFile = File(rootDirectory, gameType.entryPoint)

    var showControls by remember {
        mutableStateOf(true)
    }

    var showMenu by remember {
        mutableStateOf(false)
    }

    /*
     * Release every synthetic key whenever the menu is opened.
     * This prevents a held virtual button from remaining pressed while
     * the game is paused behind the menu.
     */
    LaunchedEffect(showMenu) {
        if (showMenu) {
            onReleaseAllKeys()
        }
    }

    /*
     * Release keys when the orientation changes. The layout can be
     * replaced during recomposition, so no old pointer is allowed to
     * keep a key alive.
     */
    val configuration = LocalConfiguration.current

    LaunchedEffect(configuration.orientation) {
        onReleaseAllKeys()
    }

    Box(
        modifier = Modifier
            .fillMaxSize()
            .background(Color.Black)
    ) {
        HtmlWebView(
            entryFile = entryFile,
            onWebViewCreated = onWebViewCreated
        )

        if (showControls && !showMenu) {
            HtmlControls(
                entry = entry,
                layoutLibrary = layoutLibrary,
                onKeyDown = onKeyDown,
                onKeyUp = onKeyUp,
                onMenu = {
                    showMenu = true
                }
            )
        }

        if (showMenu) {
            HtmlMenu(
                controlsVisible = showControls,
                onResume = {
                    showMenu = false
                },
                onToggleControls = {
                    showControls = !showControls
                    showMenu = false
                },
                onExit = {
                    showMenu = false
                    onExit()
                }
            )
        }
    }
}

@SuppressLint("SetJavaScriptEnabled")
@Composable
private fun HtmlWebView(
    entryFile: File,
    onWebViewCreated: (WebView) -> Unit
) {
    AndroidView(
        modifier = Modifier.fillMaxSize(),

        factory = { context ->
            WebView(context).apply {
                onWebViewCreated(this)

                setBackgroundColor(AndroidColor.BLACK)

                settings.apply {
                    javaScriptEnabled = true
                    domStorageEnabled = true
                    databaseEnabled = true

                    allowFileAccess = true
                    allowContentAccess = true

                    /*
                     * HTML games commonly load JavaScript, JSON, images,
                     * audio and other files from sibling directories.
                     */
                    allowFileAccessFromFileURLs = true
                    allowUniversalAccessFromFileURLs = true

                    javaScriptCanOpenWindowsAutomatically = true
                    mediaPlaybackRequiresUserGesture = false

                    useWideViewPort = true
                    loadWithOverviewMode = true

                    builtInZoomControls = false
                    displayZoomControls = false
                    setSupportZoom(false)

                    cacheMode = WebSettings.LOAD_DEFAULT

                    userAgentString =
                        "$userAgentString SpaghettiHTMLRunner/1.0"
                }

                webChromeClient = WebChromeClient()

                webViewClient = object : WebViewClient() {

                    override fun shouldOverrideUrlLoading(
                        view: WebView,
                        request: WebResourceRequest
                    ): Boolean {
                        return when (request.url.scheme?.lowercase()) {
                            "file",
                            "http",
                            "https" -> false

                            else -> true
                        }
                    }
                }

                systemUiVisibility =
                    View.SYSTEM_UI_FLAG_FULLSCREEN or
                        View.SYSTEM_UI_FLAG_HIDE_NAVIGATION or
                        View.SYSTEM_UI_FLAG_IMMERSIVE_STICKY or
                        View.SYSTEM_UI_FLAG_LAYOUT_FULLSCREEN or
                        View.SYSTEM_UI_FLAG_LAYOUT_HIDE_NAVIGATION or
                        View.SYSTEM_UI_FLAG_LAYOUT_STABLE

                if (entryFile.exists()) {
                    loadUrl(entryFile.toURI().toString())
                }
            }
        }
    )
}

@Composable
private fun HtmlControls(
    entry: GameEntry,
    layoutLibrary: LayoutLibrary,
    onKeyDown: (Int) -> Unit,
    onKeyUp: (Int) -> Unit,
    onMenu: () -> Unit
) {
    val configuration = LocalConfiguration.current

    val isLandscape =
        configuration.orientation == Configuration.ORIENTATION_LANDSCAPE

    val layoutId =
        if (isLandscape) {
            entry.landscapeLayout
        } else {
            entry.portraitLayout
        }

    val fallbackId =
        if (isLandscape) {
            LayoutLibrary.DEFAULT_LANDSCAPE_LAYOUT
        } else {
            LayoutLibrary.DEFAULT_PORTRAIT_LAYOUT
        }

    val layout =
        layoutLibrary.findById(layoutId)
            ?: layoutLibrary.findById(fallbackId)
            ?: return

    BoxWithConstraints(
        modifier = Modifier.fillMaxSize()
    ) {
        layout.elements.forEach { element ->
            when (element) {

                is GamepadElement.Key -> {
                    HtmlKeyButton(
                        element = element,
                        onKeyDown = onKeyDown,
                        onKeyUp = onKeyUp,
                        modifier = placementForElement(element)
                    )
                }

                is GamepadElement.Joystick -> {
                    HtmlJoystick(
                        element = element,
                        onKeyDown = onKeyDown,
                        onKeyUp = onKeyUp,
                        modifier = placementForElement(element)
                    )
                }

                is GamepadElement.Menu -> {
                    HtmlMenuButton(
                        element = element,
                        onClick = onMenu,
                        modifier = placementForElement(element)
                    )
                }

                /*
                 * HTML games are keyboard/DOM-input based in 1.0.
                 *
                 * Analog joystick input and GameMaker-specific mouse/
                 * fast-forward controls belong to the native runner.
                 */
                is GamepadElement.AnalogJoystick -> Unit

                is GamepadElement.MouseButton -> Unit

                is GamepadElement.FastForward -> Unit
            }
        }
    }
}

@Composable
private fun BoxWithConstraintsScope.placementForElement(
    element: GamepadElement
): Modifier {
    val referenceSize =
        if (maxWidth < maxHeight) {
            maxWidth
        } else {
            maxHeight
        }

    val size = referenceSize * element.scale.toFloat()

    val x =
        maxWidth * element.positionX.toFloat() -
            size / 2f

    val y =
        maxHeight * element.positionY.toFloat() -
            size / 2f

    return Modifier
        .offset(
            x = x,
            y = y
        )
        .size(size)
        .alpha(element.opacity.toFloat())
}

@Composable
private fun HtmlKeyButton(
    element: GamepadElement.Key,
    onKeyDown: (Int) -> Unit,
    onKeyUp: (Int) -> Unit,
    modifier: Modifier
) {
    val binding = element.binding as? InputBinding.Keyboard
        ?: return

    val label =
        element.label
            ?: htmlKeyLabel(binding.vk)

    Box(
        modifier = modifier
            .background(
                Color(0xAA222222),
                CircleShape
            )
            .pointerInput(binding.vk) {
                awaitEachGesture {
                    awaitFirstDown(
                        requireUnconsumed = false
                    )

                    onKeyDown(binding.vk)

                    try {
                        waitForUpOrCancellation()
                    } finally {
                        onKeyUp(binding.vk)
                    }
                }
            },
        contentAlignment = Alignment.Center
    ) {
        Text(
            text = label,
            color = Color.White,
            fontSize = 18.sp
        )
    }
}

@Composable
private fun HtmlJoystick(
    element: GamepadElement.Joystick,
    onKeyDown: (Int) -> Unit,
    onKeyUp: (Int) -> Unit,
    modifier: Modifier
) {
    Box(
        modifier = modifier,
        contentAlignment = Alignment.Center
    ) {
        Column(
            horizontalAlignment = Alignment.CenterHorizontally
        ) {
            HtmlDirectionalButton(
                binding = element.up,
                label = "▲",
                onKeyDown = onKeyDown,
                onKeyUp = onKeyUp,
                modifier = Modifier.size(42.dp)
            )

            Row(
                verticalAlignment = Alignment.CenterVertically
            ) {
                HtmlDirectionalButton(
                    binding = element.left,
                    label = "◀",
                    onKeyDown = onKeyDown,
                    onKeyUp = onKeyUp,
                    modifier = Modifier.size(42.dp)
                )

                Box(
                    modifier = Modifier
                        .size(42.dp)
                        .background(
                            Color(0xAA222222),
                            CircleShape
                        )
                )

                HtmlDirectionalButton(
                    binding = element.right,
                    label = "▶",
                    onKeyDown = onKeyDown,
                    onKeyUp = onKeyUp,
                    modifier = Modifier.size(42.dp)
                )
            }

            HtmlDirectionalButton(
                binding = element.down,
                label = "▼",
                onKeyDown = onKeyDown,
                onKeyUp = onKeyUp,
                modifier = Modifier.size(42.dp)
            )
        }
    }
}

@Composable
private fun HtmlDirectionalButton(
    binding: InputBinding,
    label: String,
    onKeyDown: (Int) -> Unit,
    onKeyUp: (Int) -> Unit,
    modifier: Modifier
) {
    val keyboard =
        binding as? InputBinding.Keyboard
            ?: return

    Box(
        modifier = modifier
            .background(
                Color(0xAA222222),
                CircleShape
            )
            .pointerInput(keyboard.vk) {
                awaitEachGesture {
                    awaitFirstDown(
                        requireUnconsumed = false
                    )

                    onKeyDown(keyboard.vk)

                    try {
                        waitForUpOrCancellation()
                    } finally {
                        onKeyUp(keyboard.vk)
                    }
                }
            },
        contentAlignment = Alignment.Center
    ) {
        Text(
            text = label,
            color = Color.White,
            fontSize = 18.sp
        )
    }
}

@Composable
private fun HtmlMenuButton(
    element: GamepadElement.Menu,
    onClick: () -> Unit,
    modifier: Modifier
) {
    Box(
        modifier = modifier
            .background(
                Color(0xAA222222),
                CircleShape
            )
            .pointerInput(Unit) {
                awaitEachGesture {
                    awaitFirstDown(
                        requireUnconsumed = false
                    )

                    waitForUpOrCancellation()
                    onClick()
                }
            },
        contentAlignment = Alignment.Center
    ) {
        Text(
            text = "☰",
            color = Color.White,
            fontSize = 18.sp
        )
    }
}

@Composable
private fun HtmlMenu(
    controlsVisible: Boolean,
    onResume: () -> Unit,
    onToggleControls: () -> Unit,
    onExit: () -> Unit
) {
    BackHandler {
        onResume()
    }

    Box(
        modifier = Modifier
            .fillMaxSize()
            .background(
                Color.Black.copy(alpha = 0.75f)
            ),
        contentAlignment = Alignment.Center
    ) {
        Column(
            horizontalAlignment = Alignment.CenterHorizontally
        ) {
            HtmlMenuAction(
                text = "Resume",
                onClick = onResume
            )

            HtmlMenuAction(
                text = if (controlsVisible) {
                    "Hide Controls"
                } else {
                    "Show Controls"
                },
                onClick = onToggleControls
            )

            HtmlMenuAction(
                text = "Exit Game",
                onClick = onExit
            )
        }
    }
}

@Composable
private fun HtmlMenuAction(
    text: String,
    onClick: () -> Unit
) {
    Box(
        modifier = Modifier
            .size(
                width = 220.dp,
                height = 56.dp
            )
            .background(
                Color(0xDD222222),
                CircleShape
            )
            .pointerInput(Unit) {
                awaitEachGesture {
                    awaitFirstDown(
                        requireUnconsumed = false
                    )

                    waitForUpOrCancellation()
                    onClick()
                }
            },
        contentAlignment = Alignment.Center
    ) {
        Text(
            text = text,
            color = Color.White,
            fontSize = 18.sp
        )
    }
}

private fun htmlKeyLabel(vk: Int): String {
    return when (vk) {
        37 -> "←"
        38 -> "↑"
        39 -> "→"
        40 -> "↓"

        13 -> "Enter"
        27 -> "Esc"
        32 -> "Space"
        8 -> "Backspace"
        9 -> "Tab"

        16 -> "Shift"
        17 -> "Ctrl"
        18 -> "Alt"

        65 -> "A"
        66 -> "B"
        67 -> "C"
        68 -> "D"
        69 -> "E"
        70 -> "F"
        71 -> "G"
        72 -> "H"
        73 -> "I"
        74 -> "J"
        75 -> "K"
        76 -> "L"
        77 -> "M"
        78 -> "N"
        79 -> "O"
        80 -> "P"
        81 -> "Q"
        82 -> "R"
        83 -> "S"
        84 -> "T"
        85 -> "U"
        86 -> "V"
        87 -> "W"
        88 -> "X"
        89 -> "Y"
        90 -> "Z"

        48 -> "0"
        49 -> "1"
        50 -> "2"
        51 -> "3"
        52 -> "4"
        53 -> "5"
        54 -> "6"
        55 -> "7"
        56 -> "8"
        57 -> "9"

        else -> vk.toString()
    }
}

/**
 * Tracks synthetic keyboard state for the WebView.
 *
 * Reference counting is important because two simultaneous fingers can
 * legally target the same keyboard binding. The key must only be released
 * after every pointer using that binding has released it.
 */
private class HtmlKeyState {

    private val references = HashMap<Int, Int>()

    fun press(
        webView: WebView,
        vk: Int
    ) {
        val oldCount = references[vk] ?: 0
        val newCount = oldCount + 1

        references[vk] = newCount

        if (oldCount == 0) {
            dispatch(webView, vk, true)
        }
    }

    fun release(
        webView: WebView,
        vk: Int
    ) {
        val oldCount = references[vk] ?: return
        val newCount = oldCount - 1

        if (newCount <= 0) {
            references.remove(vk)
            dispatch(webView, vk, false)
        } else {
            references[vk] = newCount
        }
    }

    fun releaseAll(
        webView: WebView?
    ) {
        if (webView == null) {
            references.clear()
            return
        }

        val keys = references.keys.toList()

        references.clear()

        for (vk in keys) {
            dispatch(webView, vk, false)
        }
    }

    fun clear() {
        references.clear()
    }

    private fun dispatch(
        webView: WebView,
        vk: Int,
        pressed: Boolean
    ) {
        val data = keyData(vk) ?: return

        val eventType =
            if (pressed) {
                "keydown"
            } else {
                "keyup"
            }

        val key = JSONObject.quote(data.key)
        val code = JSONObject.quote(data.code)

        val script = """
            (() => {
                const event = new KeyboardEvent("$eventType", {
                    key: $key,
                    code: $code,
                    bubbles: true,
                    cancelable: true
                });

                try {
                    Object.defineProperty(event, "keyCode", {
                        get: () => ${data.keyCode}
                    });

                    Object.defineProperty(event, "which", {
                        get: () => ${data.keyCode}
                    });

                    Object.defineProperty(event, "charCode", {
                        get: () => ${data.keyCode}
                    });
                } catch (_) {
                }

                window.dispatchEvent(event);

                document.dispatchEvent(event);

                if (document.body) {
                    document.body.dispatchEvent(event);
                }

                if (document.activeElement) {
                    document.activeElement.dispatchEvent(event);
                }
            })();
        """.trimIndent()

        webView.post {
            if (!webView.isAttachedToWindow) {
                return@post
            }

            webView.evaluateJavascript(
                script,
                null
            )
        }
    }

    private fun keyData(vk: Int): KeyData? {
        return when (vk) {
            37 -> KeyData("ArrowLeft", "ArrowLeft", 37)
            38 -> KeyData("ArrowUp", "ArrowUp", 38)
            39 -> KeyData("ArrowRight", "ArrowRight", 39)
            40 -> KeyData("ArrowDown", "ArrowDown", 40)

            13 -> KeyData("Enter", "Enter", 13)
            27 -> KeyData("Escape", "Escape", 27)
            32 -> KeyData(" ", "Space", 32)
            8 -> KeyData("Backspace", "Backspace", 8)
            9 -> KeyData("Tab", "Tab", 9)

            16 -> KeyData("Shift", "ShiftLeft", 16)
            17 -> KeyData("Control", "ControlLeft", 17)
            18 -> KeyData("Alt", "AltLeft", 18)

            in 65..90 -> {
                val letter =
                    ('A'.code + (vk - 65)).toChar()

                KeyData(
                    key = letter.toString().lowercase(),
                    code = "Key$letter",
                    keyCode = vk
                )
            }

            in 48..57 -> {
                val number =
                    ('0'.code + (vk - 48)).toChar()

                KeyData(
                    key = number.toString(),
                    code = "Digit$number",
                    keyCode = vk
                )
            }

            else -> null
        }
    }

    private data class KeyData(
        val key: String,
        val code: String,
        val keyCode: Int
    )
}
