package net.perfectdreams.butterscotch.android.runtime

import android.content.Context
import android.net.Uri
import android.view.KeyEvent
import android.view.MotionEvent
import android.view.View
import net.perfectdreams.butterscotch.android.library.GameEntry
import net.perfectdreams.butterscotch.android.library.GameLibrary
import java.io.File

/**
 * Central contract for every engine hosted inside Spaghetti.
 *
 * Important design rule:
 * - Spaghetti owns the UI, overlays, controls, navigation, and lifecycle.
 * - Each engine owns only the execution/rendering behavior for its game format.
 * - All engines receive the same input model: physical keyboard, physical controller,
 *   touch, and virtual on-screen controls are translated by the host before reaching
 *   the engine.
 *
 * GameMaker remains external for now through the existing Butterscotch path.
 * Flash, RPG Maker, HTML, and any future engine should adapt to this same contract.
 */
enum class EngineKind(
    val displayName: String
) {
    GAME_MAKER("GameMaker"),
    FLASH("Adobe Flash"),
    RPG_MAKER("RPG Maker"),
    HTML("HTML5")
}

/**
 * Maps the imported game type to the runtime family that should execute it.
 */
val GameEntry.GameType.engineKind: EngineKind
    get() = when (this) {
        is GameEntry.GameType.GameMakerStudio -> EngineKind.GAME_MAKER
        is GameEntry.GameType.Flash -> EngineKind.FLASH
        is GameEntry.GameType.RPGMaker -> EngineKind.RPG_MAKER
        is GameEntry.GameType.OldRPGM -> EngineKind.RPG_MAKER
        is GameEntry.GameType.Html -> EngineKind.HTML
    }

/**
 * Full launch context for an engine session.
 *
 * This stays intentionally generic so the same host logic can be used by
 * Ruffle, mkxp-z, EasyRPG, WebView HTML, and later engines.
 */
data class EngineSessionContext(
    val appContext: Context,
    val entry: GameEntry,
    val library: GameLibrary,
    val gameDir: File,
    val bundleDir: File,
    val savesDir: File,
    val logsDir: File
) {
    val primaryFile: File
        get() = library.primaryFile(entry)

    val assetDir: File
        get() = library.assetsDir(entry)
}

/**
 * Events generated by the Spaghetti UI and forwarded to the active engine.
 *
 * The goal is to keep the host-level controls visually consistent while allowing each
 * engine to decide how to consume the same normalized input.
 */
sealed interface EngineControlEvent {

    data object BackPressed : EngineControlEvent
    data object MenuPressed : EngineControlEvent
    data object PausePressed : EngineControlEvent
    data object ResumePressed : EngineControlEvent
    data object ToggleVirtualControls : EngineControlEvent
    data object ToggleFullscreen : EngineControlEvent
    data object ShowKeyboard : EngineControlEvent
    data object HideKeyboard : EngineControlEvent
    data object RequestExitToLibrary : EngineControlEvent

    data class VirtualButtonPressed(
        val id: String
    ) : EngineControlEvent

    data class VirtualButtonReleased(
        val id: String
    ) : EngineControlEvent

    data class VirtualAxisChanged(
        val id: String,
        val x: Float,
        val y: Float
    ) : EngineControlEvent

    data class VirtualPointerChanged(
        val x: Float,
        val y: Float,
        val pressed: Boolean
    ) : EngineControlEvent

    data class TextInput(
        val text: String
    ) : EngineControlEvent
}

/**
 * Unified input sink that engines can implement.
 *
 * Spaghetti routes all physical and virtual input through the host, then calls these hooks.
 * That way, every engine receives the same control model instead of each app inventing its own.
 */
interface EngineInputSink {
    fun onKeyEvent(event: KeyEvent): Boolean = false
    fun onTouchEvent(event: MotionEvent): Boolean = false
    fun onGenericMotionEvent(event: MotionEvent): Boolean = false
    fun onControlEvent(event: EngineControlEvent): Boolean = false
}

/**
 * Host-to-engine callbacks.
 *
 * The engine can ask the host to show/hide overlay pieces, open the keyboard, show a message,
 * or surface a fatal error. The host decides the final UI behavior.
 */
interface EngineHostCallbacks {
    fun requestFinish()
    fun requestExitToLibrary()

    fun setVirtualControlsVisible(visible: Boolean)
    fun setSystemBarsVisible(visible: Boolean)
    fun setPointerVisible(visible: Boolean)
    fun requestTextInput(visible: Boolean)

    fun showMessage(message: String)
    fun openExternalUri(uri: Uri)
    fun reportFatalError(message: String, throwable: Throwable? = null)
}

/**
 * One runtime implementation per engine.
 *
 * The engine may return any Android View that it needs: SurfaceView, TextureView, WebView,
 * a custom container, or a composite view. The Spaghetti screen will place that inside the
 * same shared game area where the current GameMaker runner lives.
 */
interface RuntimeEngine : EngineInputSink {
    val kind: EngineKind
    val displayName: String

    fun createView(
        context: EngineSessionContext,
        callbacks: EngineHostCallbacks
    ): View

    fun onResume() {}
    fun onPause() {}
    fun onStop() {}
    fun onDestroy() {}

    /**
     * Give the engine a chance to consume back navigation before the host handles it.
     */
    fun onBackPressed(): Boolean = false
}

/**
 * Small helper to resolve the engine family directly from a game entry.
 */
object RuntimeEngineResolver {
    fun resolveKind(gameType: GameEntry.GameType): EngineKind = gameType.engineKind

    fun supports(gameType: GameEntry.GameType, kind: EngineKind): Boolean =
        resolveKind(gameType) == kind
}

/**
 * Extra utility for the host side.
 */
object RuntimeSessionFiles {
    fun resolveGameDir(library: GameLibrary, entry: GameEntry): File = library.gameDir(entry.id)
    fun resolveBundleDir(library: GameLibrary, entry: GameEntry): File = library.bundleDir(entry)
    fun resolveSavesDir(library: GameLibrary, entry: GameEntry): File = library.savesDir(entry)
    fun resolveLogsDir(library: GameLibrary, entry: GameEntry): File = library.logsDir(entry)
}
